### ISSUE TITLE
TypeError: Cannot convert tz-naive timestamps, use tz_localize to localize

### ISSUE THREAD

**Issue by davidusb-geek** [DavidMStraub/HiBro#1]
Hi, your project seems like a very nice tool.
However when I launch hibro and I go to 127.0.0.1:8456 I'm getting this error with time zone naive timestamps.
Can you please help me on getting this to work. Thank you in advance for your help.
I'm using Home assistant on Python virtual env on Ubuntu 16.04.
I leave you the full traceback of the error:

Traceback (most recent call last)
File "/home/davidusb/.local/lib/python3.7/site-packages/flask/app.py", line 2463, in __call__
return self.wsgi_app(environ, start_response)
File "/home/davidusb/.local/lib/python3.7/site-packages/flask/app.py", line 2449, in wsgi_app
response = self.handle_exception(e)
File "/home/davidusb/.local/lib/python3.7/site-packages/flask/app.py", line 1866, in handle_exception
reraise(exc_type, exc_value, tb)
File "/home/davidusb/.local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
raise value
File "/home/davidusb/.local/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
response = self.full_dispatch_request()
File "/home/davidusb/.local/lib/python3.7/site-packages/flask/app.py", line 1944, in full_dispatch_request
self.try_trigger_before_first_request_functions()
File "/home/davidusb/.local/lib/python3.7/site-packages/flask/app.py", line 1992, in try_trigger_before_first_request_functions
func()
File "/home/davidusb/.local/lib/python3.7/site-packages/dash/dash.py", line 1502, in _setup_server
self._validate_layout()
File "/home/davidusb/.local/lib/python3.7/site-packages/dash/dash.py", line 1473, in _validate_layout
to_validate = self._layout_value()
File "/home/davidusb/.local/lib/python3.7/site-packages/dash/dash.py", line 444, in _layout_value
self._cached_layout = self._layout()
File "/home/davidusb/.local/lib/python3.7/site-packages/hibro/dashboard.py", line 43, in get_layout
elements += [Line(engine=self.engine, config=element).graph()]
File "/home/davidusb/.local/lib/python3.7/site-packages/hibro/plot.py", line 110, in graph
_, _unit = self.trace(fig, entity_config)
File "/home/davidusb/.local/lib/python3.7/site-packages/hibro/plot.py", line 93, in trace
name, unit, data = self.data_entity(entity_config)
File "/home/davidusb/.local/lib/python3.7/site-packages/hibro/plot.py", line 55, in data_entity
aggregate=aggregate,
File "/home/davidusb/.local/lib/python3.7/site-packages/hibro/data.py", line 93, in get_data
df.loc[:, "time"] = df.loc[:, "time"].dt.tz_convert(tzlocal.get_localzone())
File "/home/davidusb/.local/lib/python3.7/site-packages/pandas/core/accessor.py", line 99, in f
return self._delegate_method(name, *args, **kwargs)
File "/home/davidusb/.local/lib/python3.7/site-packages/pandas/core/indexes/accessors.py", line 103, in _delegate_method
result = method(*args, **kwargs)
File "/home/davidusb/.local/lib/python3.7/site-packages/pandas/core/accessor.py", line 99, in f
return self._delegate_method(name, *args, **kwargs)
File "/home/davidusb/.local/lib/python3.7/site-packages/pandas/core/indexes/datetimelike.py", line 910, in _delegate_method
result = operator.methodcaller(name, *args, **kwargs)(self._data)
File "/home/davidusb/.local/lib/python3.7/site-packages/pandas/core/arrays/datetimes.py", line 818, in tz_convert
"Cannot convert tz-naive timestamps, use tz_localize to localize"
TypeError: Cannot convert tz-naive timestamps, use tz_localize to localize

**Comment by DavidMStraub** [comment]
Hi, sorry for overlooking this issue.

To understand better what is happening: can you please check whether the timestamps are stored in your database in your local time or in UTC?

**Comment by davidusb-geek** [comment]
Hi,
In mi configuration.yaml I have: 
`time_zone: Europe/Paris`
So it is time zone aware right?

**Comment by DavidMStraub** [comment]
I would like to see the value in your history database directly...

**Comment by davidusb-geek** [comment]
Ok, using a sqlite3 query directly on a sensor in my database I was able to extract the following timestamp:
`"2020-01-26 23:08:58.546494",26.88
`

**Comment by DavidMStraub** [comment]
Great, thanks. Now the question was: do these (TZ-naive) timestamps refer to UTC or your local TZ?

**Comment by davidusb-geek** [comment]
Ok, I just checked and they are definitely UTC. They are shifted -2h from my local TZ.

**Comment by DavidMStraub** [comment]
Great, that was the info I needed. I believe the change in the above commit fixes the issue, can you please confirm?

**Comment by davidusb-geek** [comment]
No luck, still getting this:

`
Traceback (most recent call last):
  File "/home/davidusb/.local/lib/python3.6/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/davidusb/.local/lib/python3.6/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/home/davidusb/.local/lib/python3.6/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/davidusb/.local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/davidusb/.local/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/davidusb/.local/lib/python3.6/site-packages/flask/app.py", line 1945, in full_dispatch_request
    self.try_trigger_before_first_request_functions()
  File "/home/davidusb/.local/lib/python3.6/site-packages/flask/app.py", line 1993, in try_trigger_before_first_request_functions
    func()
  File "/home/davidusb/.local/lib/python3.6/site-packages/dash/dash.py", line 1049, in _setup_server
    _validate.validate_layout(self.layout, self._layout_value())
  File "/home/davidusb/.local/lib/python3.6/site-packages/dash/dash.py", line 440, in _layout_value
    return self._layout() if self._layout_is_function else self._layout
  File "/home/davidusb/.local/lib/python3.6/site-packages/hibro/dashboard.py", line 43, in get_layout
    elements += [Line(engine=self.engine, config=element).graph()]
  File "/home/davidusb/.local/lib/python3.6/site-packages/hibro/plot.py", line 110, in graph
    _, _unit = self.trace(fig, entity_config)
  File "/home/davidusb/.local/lib/python3.6/site-packages/hibro/plot.py", line 93, in trace
    name, unit, data = self.data_entity(entity_config)
  File "/home/davidusb/.local/lib/python3.6/site-packages/hibro/plot.py", line 55, in data_entity
    aggregate=aggregate,
  File "/home/davidusb/.local/lib/python3.6/site-packages/hibro/data.py", line 98, in get_data
    df.loc[:, "time"] = df.loc[:, "time"].dt.tz_convert(tzlocal.get_localzone())
  File "/home/davidusb/.local/lib/python3.6/site-packages/pandas/core/accessor.py", line 99, in f
    return self._delegate_method(name, *args, **kwargs)
  File "/home/davidusb/.local/lib/python3.6/site-packages/pandas/core/indexes/accessors.py", line 103, in _delegate_method
    result = method(*args, **kwargs)
  File "/home/davidusb/.local/lib/python3.6/site-packages/pandas/core/accessor.py", line 99, in f
    return self._delegate_method(name, *args, **kwargs)
  File "/home/davidusb/.local/lib/python3.6/site-packages/pandas/core/indexes/datetimelike.py", line 905, in _delegate_method
    result = operator.methodcaller(name, *args, **kwargs)(self._data)
  File "/home/davidusb/.local/lib/python3.6/site-packages/pandas/core/arrays/datetimes.py", line 820, in tz_convert
    "Cannot convert tz-naive timestamps, use tz_localize to localize"
TypeError: Cannot convert tz-naive timestamps, use tz_localize to localize
`

**Comment by DavidMStraub** [comment]
Oh sorry, my bad. Now?

**Comment by davidusb-geek** [comment]
Yes! Perfect it is working fine now.
Thank you for your help solving this issue. Great work ;-)
